export class PreInspection {
  PROTECTORS_IN_PLACE_COMMENT: string;
  PROTECTORS_IN_PLACE_DESC: string;
  PROTECTORS_IN_PLACE_STATE: string;
  PROTECTORS_IN_PLACE_STEP: string;
  IDENTIFY_TAG_AND_SERIAL_COMMENT: string;
  IDENTIFY_TAG_AND_SERIAL_DESC: string;
  IDENTIFY_TAG_AND_SERIAL_STATE: string;
  IDENTIFY_TAG_AND_SERIAL_STEP: string;
  REMOVE_AND_DEGREASE_COMMENT: string;
  REMOVE_AND_DEGREASE_DESC: string;
  REMOVE_AND_DEGREASE_STATE: string;
  REMOVE_AND_DEGREASE_STEP: string;
  VISUAL_PIN_AND_BOX_COMMENT: string;
  VISUAL_PIN_AND_BOX_DESC: string;
  VISUAL_PIN_AND_BOX_STATE: string;
  VISUAL_PIN_AND_BOX_STEP: string;
  VISUAL_FINS_GUARD_COLLAR_CLAMPS_COMMENT: string;
  VISUAL_FINS_GUARD_COLLAR_CLAMPS_DESC: string;
  VISUAL_FINS_GUARD_COLLAR_CLAMPS_STATE: string;
  VISUAL_FINS_GUARD_COLLAR_CLAMPS_STEP: string;
  VISUAL_ANODE_CLAMP_JEWEL_COMMENT: string;
  VISUAL_ANODE_CLAMP_JEWEL_DESC: string;
  VISUAL_ANODE_CLAMP_JEWEL_STATE: string;
  VISUAL_ANODE_CLAMP_JEWEL_STEP: string;
	STATUS: string;
  complete: boolean;
}
