export class PostInspection {
  BLOW_OUT_LINES_COMMENT: string;
  BLOW_OUT_LINES_DESC: string;
  BLOW_OUT_LINES_STATE: string;
  BLOW_OUT_LINES_STEP: string;
  FIT_SEALS_COMMENT: string;
  FIT_SEALS_DESC: string;
  FIT_SEALS_STATE: string;
  FIT_SEALS_STEP: string;
  PRESERVATION_DONE_COMMENT: string;
  PRESERVATION_DONE_DESC: string;
  PRESERVATION_DONE_STATE: string;
  PRESERVATION_DONE_STEP: string;
  JEWEL_INSTALLED_AND_SECURE_COMMENT: string;
  JEWEL_INSTALLED_AND_SECURE_DESC: string;
  JEWEL_INSTALLED_AND_SECURE_STATE: string;
  JEWEL_INSTALLED_AND_SECURE_STEP: string;
  CHECK_FASTENER_MARKINGS_COMMENT: string;
  CHECK_FASTENER_MARKINGS_DESC: string;
  CHECK_FASTENER_MARKINGS_STATE: string;
  CHECK_FASTENER_MARKINGS_STEP: string;
  FIT_PROTECTIVE_COVERS_COMMENT: string;
  FIT_PROTECTIVE_COVERS_DESC: string;
  FIT_PROTECTIVE_COVERS_STATE: string;
  FIT_PROTECTIVE_COVERS_STEP: string;
  STATUS: string;
  complete: boolean;
}
